name: Meu Primeiro Workflow de CI

on:
  
  push:
    branches: [ "main" ]
    paths-ignore:
      - README.md
  
  
  workflow_dispatch:


jobs:
  
  meu-primeiro-job:
    
    runs-on: ubuntu-latest


    steps:
      - name: RA - Nome
        run: echo "6324647 Gabriel Santiago De Andrade"
      - name: Mostra o diretório de trabalho
        run: pwd
      - name: Imprime o nome do repositório
        run: echo "Nome do repositório: $GITHUB_REPOSITORY"